{{- if and .Values.enabled (eq (include "redis.authEnabled" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.secretName" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "redis.secretName" .) }}
{{- if $existing }}
data:
{{- range $k, $v := $existing.data }}
  {{ $k }}: {{ $v }}
{{- end }}
{{- else }}
stringData:
  redis-password: {{ .Values.auth.password | default (randAlphaNum 32) | quote }}
{{- end }}
{{- end }}
