{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.name" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cache
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: 6379
{{- end }}
