// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: iterabase/gateway/v1/gateway.proto

package gatewayv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nunocgoncalves/control-plane/internal/gatewayrpc/iterabase/gateway/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RunnerServiceName is the fully-qualified name of the RunnerService service.
	RunnerServiceName = "iterabase.gateway.v1.RunnerService"
	// GatewayServiceName is the fully-qualified name of the GatewayService service.
	GatewayServiceName = "iterabase.gateway.v1.GatewayService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RunnerServiceRegisterRunnerProcedure is the fully-qualified name of the RunnerService's
	// RegisterRunner RPC.
	RunnerServiceRegisterRunnerProcedure = "/iterabase.gateway.v1.RunnerService/RegisterRunner"
	// GatewayServiceDiscoverEffectiveToolsProcedure is the fully-qualified name of the GatewayService's
	// DiscoverEffectiveTools RPC.
	GatewayServiceDiscoverEffectiveToolsProcedure = "/iterabase.gateway.v1.GatewayService/DiscoverEffectiveTools"
	// GatewayServiceInvokeToolProcedure is the fully-qualified name of the GatewayService's InvokeTool
	// RPC.
	GatewayServiceInvokeToolProcedure = "/iterabase.gateway.v1.GatewayService/InvokeTool"
	// GatewayServiceCancelInvocationProcedure is the fully-qualified name of the GatewayService's
	// CancelInvocation RPC.
	GatewayServiceCancelInvocationProcedure = "/iterabase.gateway.v1.GatewayService/CancelInvocation"
)

// RunnerServiceClient is a client for the iterabase.gateway.v1.RunnerService service.
type RunnerServiceClient interface {
	// RegisterRunner is the one long-lived bidi stream per runner. Runner->CP:
	// Register, Heartbeat, InvokeResult, InvokeError. CP->runner: Welcome,
	// Invoke, Cancel, Ack. A runner may register multiple immutable tool
	// versions; each (tool, version) resolves to an exact digest. Heartbeats
	// drive availability; a stale lease excludes the version from new-attempt
	// resolution without disturbing pinned active attempts.
	RegisterRunner(context.Context) *connect.BidiStreamForClient[v1.RunnerMessage, v1.RunnerControl]
}

// NewRunnerServiceClient constructs a client for the iterabase.gateway.v1.RunnerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRunnerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RunnerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runnerServiceMethods := v1.File_iterabase_gateway_v1_gateway_proto.Services().ByName("RunnerService").Methods()
	return &runnerServiceClient{
		registerRunner: connect.NewClient[v1.RunnerMessage, v1.RunnerControl](
			httpClient,
			baseURL+RunnerServiceRegisterRunnerProcedure,
			connect.WithSchema(runnerServiceMethods.ByName("RegisterRunner")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runnerServiceClient implements RunnerServiceClient.
type runnerServiceClient struct {
	registerRunner *connect.Client[v1.RunnerMessage, v1.RunnerControl]
}

// RegisterRunner calls iterabase.gateway.v1.RunnerService.RegisterRunner.
func (c *runnerServiceClient) RegisterRunner(ctx context.Context) *connect.BidiStreamForClient[v1.RunnerMessage, v1.RunnerControl] {
	return c.registerRunner.CallBidiStream(ctx)
}

// RunnerServiceHandler is an implementation of the iterabase.gateway.v1.RunnerService service.
type RunnerServiceHandler interface {
	// RegisterRunner is the one long-lived bidi stream per runner. Runner->CP:
	// Register, Heartbeat, InvokeResult, InvokeError. CP->runner: Welcome,
	// Invoke, Cancel, Ack. A runner may register multiple immutable tool
	// versions; each (tool, version) resolves to an exact digest. Heartbeats
	// drive availability; a stale lease excludes the version from new-attempt
	// resolution without disturbing pinned active attempts.
	RegisterRunner(context.Context, *connect.BidiStream[v1.RunnerMessage, v1.RunnerControl]) error
}

// NewRunnerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRunnerServiceHandler(svc RunnerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runnerServiceMethods := v1.File_iterabase_gateway_v1_gateway_proto.Services().ByName("RunnerService").Methods()
	runnerServiceRegisterRunnerHandler := connect.NewBidiStreamHandler(
		RunnerServiceRegisterRunnerProcedure,
		svc.RegisterRunner,
		connect.WithSchema(runnerServiceMethods.ByName("RegisterRunner")),
		connect.WithHandlerOptions(opts...),
	)
	return "/iterabase.gateway.v1.RunnerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RunnerServiceRegisterRunnerProcedure:
			runnerServiceRegisterRunnerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRunnerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRunnerServiceHandler struct{}

func (UnimplementedRunnerServiceHandler) RegisterRunner(context.Context, *connect.BidiStream[v1.RunnerMessage, v1.RunnerControl]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("iterabase.gateway.v1.RunnerService.RegisterRunner is not implemented"))
}

// GatewayServiceClient is a client for the iterabase.gateway.v1.GatewayService service.
type GatewayServiceClient interface {
	// DiscoverEffectiveTools returns only the descriptors permitted for the
	// caller's active attempt/turn or workflow-step context: registered healthy
	// versions ∩ AgentPool grants ∩ workflow-requested tools ∩ pool-level
	// identity scope (ARCH-006/016/018). The disposable child never calls this;
	// the trusted supervisor does, after a turn is assigned, and passes the
	// non-secret descriptors to the child as pi-compatible stubs.
	DiscoverEffectiveTools(context.Context, *connect.Request[v1.DiscoverRequest]) (*connect.Response[v1.DiscoverResponse], error)
	// InvokeTool is the ledger-gated execution path (ARCH-014). The gateway
	// commits an invocation row (uniquely keyed by attempt + caller scope +
	// tool-call id + exact version digest + idempotency key) BEFORE dispatching
	// over the runner stream. A duplicate completed invocation returns its
	// committed result/artifact refs; a duplicate in progress reports the
	// existing invocation; a possible effect with no committed result becomes
	// outcome_unknown and is never automatically repeated.
	InvokeTool(context.Context, *connect.Request[v1.InvokeRequest]) (*connect.Response[v1.InvokeResponse], error)
	// CancelInvocation propagates cancellation to an in-flight invocation. It
	// cannot undo an effect already started (ARCH-014).
	CancelInvocation(context.Context, *connect.Request[v1.CancelRequest]) (*connect.Response[v1.CancelResponse], error)
}

// NewGatewayServiceClient constructs a client for the iterabase.gateway.v1.GatewayService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGatewayServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GatewayServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gatewayServiceMethods := v1.File_iterabase_gateway_v1_gateway_proto.Services().ByName("GatewayService").Methods()
	return &gatewayServiceClient{
		discoverEffectiveTools: connect.NewClient[v1.DiscoverRequest, v1.DiscoverResponse](
			httpClient,
			baseURL+GatewayServiceDiscoverEffectiveToolsProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("DiscoverEffectiveTools")),
			connect.WithClientOptions(opts...),
		),
		invokeTool: connect.NewClient[v1.InvokeRequest, v1.InvokeResponse](
			httpClient,
			baseURL+GatewayServiceInvokeToolProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("InvokeTool")),
			connect.WithClientOptions(opts...),
		),
		cancelInvocation: connect.NewClient[v1.CancelRequest, v1.CancelResponse](
			httpClient,
			baseURL+GatewayServiceCancelInvocationProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("CancelInvocation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gatewayServiceClient implements GatewayServiceClient.
type gatewayServiceClient struct {
	discoverEffectiveTools *connect.Client[v1.DiscoverRequest, v1.DiscoverResponse]
	invokeTool             *connect.Client[v1.InvokeRequest, v1.InvokeResponse]
	cancelInvocation       *connect.Client[v1.CancelRequest, v1.CancelResponse]
}

// DiscoverEffectiveTools calls iterabase.gateway.v1.GatewayService.DiscoverEffectiveTools.
func (c *gatewayServiceClient) DiscoverEffectiveTools(ctx context.Context, req *connect.Request[v1.DiscoverRequest]) (*connect.Response[v1.DiscoverResponse], error) {
	return c.discoverEffectiveTools.CallUnary(ctx, req)
}

// InvokeTool calls iterabase.gateway.v1.GatewayService.InvokeTool.
func (c *gatewayServiceClient) InvokeTool(ctx context.Context, req *connect.Request[v1.InvokeRequest]) (*connect.Response[v1.InvokeResponse], error) {
	return c.invokeTool.CallUnary(ctx, req)
}

// CancelInvocation calls iterabase.gateway.v1.GatewayService.CancelInvocation.
func (c *gatewayServiceClient) CancelInvocation(ctx context.Context, req *connect.Request[v1.CancelRequest]) (*connect.Response[v1.CancelResponse], error) {
	return c.cancelInvocation.CallUnary(ctx, req)
}

// GatewayServiceHandler is an implementation of the iterabase.gateway.v1.GatewayService service.
type GatewayServiceHandler interface {
	// DiscoverEffectiveTools returns only the descriptors permitted for the
	// caller's active attempt/turn or workflow-step context: registered healthy
	// versions ∩ AgentPool grants ∩ workflow-requested tools ∩ pool-level
	// identity scope (ARCH-006/016/018). The disposable child never calls this;
	// the trusted supervisor does, after a turn is assigned, and passes the
	// non-secret descriptors to the child as pi-compatible stubs.
	DiscoverEffectiveTools(context.Context, *connect.Request[v1.DiscoverRequest]) (*connect.Response[v1.DiscoverResponse], error)
	// InvokeTool is the ledger-gated execution path (ARCH-014). The gateway
	// commits an invocation row (uniquely keyed by attempt + caller scope +
	// tool-call id + exact version digest + idempotency key) BEFORE dispatching
	// over the runner stream. A duplicate completed invocation returns its
	// committed result/artifact refs; a duplicate in progress reports the
	// existing invocation; a possible effect with no committed result becomes
	// outcome_unknown and is never automatically repeated.
	InvokeTool(context.Context, *connect.Request[v1.InvokeRequest]) (*connect.Response[v1.InvokeResponse], error)
	// CancelInvocation propagates cancellation to an in-flight invocation. It
	// cannot undo an effect already started (ARCH-014).
	CancelInvocation(context.Context, *connect.Request[v1.CancelRequest]) (*connect.Response[v1.CancelResponse], error)
}

// NewGatewayServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGatewayServiceHandler(svc GatewayServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gatewayServiceMethods := v1.File_iterabase_gateway_v1_gateway_proto.Services().ByName("GatewayService").Methods()
	gatewayServiceDiscoverEffectiveToolsHandler := connect.NewUnaryHandler(
		GatewayServiceDiscoverEffectiveToolsProcedure,
		svc.DiscoverEffectiveTools,
		connect.WithSchema(gatewayServiceMethods.ByName("DiscoverEffectiveTools")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceInvokeToolHandler := connect.NewUnaryHandler(
		GatewayServiceInvokeToolProcedure,
		svc.InvokeTool,
		connect.WithSchema(gatewayServiceMethods.ByName("InvokeTool")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceCancelInvocationHandler := connect.NewUnaryHandler(
		GatewayServiceCancelInvocationProcedure,
		svc.CancelInvocation,
		connect.WithSchema(gatewayServiceMethods.ByName("CancelInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/iterabase.gateway.v1.GatewayService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GatewayServiceDiscoverEffectiveToolsProcedure:
			gatewayServiceDiscoverEffectiveToolsHandler.ServeHTTP(w, r)
		case GatewayServiceInvokeToolProcedure:
			gatewayServiceInvokeToolHandler.ServeHTTP(w, r)
		case GatewayServiceCancelInvocationProcedure:
			gatewayServiceCancelInvocationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGatewayServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGatewayServiceHandler struct{}

func (UnimplementedGatewayServiceHandler) DiscoverEffectiveTools(context.Context, *connect.Request[v1.DiscoverRequest]) (*connect.Response[v1.DiscoverResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iterabase.gateway.v1.GatewayService.DiscoverEffectiveTools is not implemented"))
}

func (UnimplementedGatewayServiceHandler) InvokeTool(context.Context, *connect.Request[v1.InvokeRequest]) (*connect.Response[v1.InvokeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iterabase.gateway.v1.GatewayService.InvokeTool is not implemented"))
}

func (UnimplementedGatewayServiceHandler) CancelInvocation(context.Context, *connect.Request[v1.CancelRequest]) (*connect.Response[v1.CancelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iterabase.gateway.v1.GatewayService.CancelInvocation is not implemented"))
}
