{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "control-plane.apiName" . }}
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
