// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: iterabase/gateway/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallerScope identifies whether this call originates from an active turn
// (supervisor) or an active workflow step (control-plane runtime). The gateway
// resolves the pool from durable state: for a turn, from the supervisor's
// SPIFFE identity cross-checked against the active turn; for a workflow step,
// from the workflow's pool binding. The caller never supplies the pool.
type CallerScope int32

const (
	CallerScope_CALLER_SCOPE_UNSPECIFIED   CallerScope = 0
	CallerScope_CALLER_SCOPE_TURN          CallerScope = 1
	CallerScope_CALLER_SCOPE_WORKFLOW_STEP CallerScope = 2
)

// Enum value maps for CallerScope.
var (
	CallerScope_name = map[int32]string{
		0: "CALLER_SCOPE_UNSPECIFIED",
		1: "CALLER_SCOPE_TURN",
		2: "CALLER_SCOPE_WORKFLOW_STEP",
	}
	CallerScope_value = map[string]int32{
		"CALLER_SCOPE_UNSPECIFIED":   0,
		"CALLER_SCOPE_TURN":          1,
		"CALLER_SCOPE_WORKFLOW_STEP": 2,
	}
)

func (x CallerScope) Enum() *CallerScope {
	p := new(CallerScope)
	*p = x
	return p
}

func (x CallerScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallerScope) Descriptor() protoreflect.EnumDescriptor {
	return file_iterabase_gateway_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (CallerScope) Type() protoreflect.EnumType {
	return &file_iterabase_gateway_v1_gateway_proto_enumTypes[0]
}

func (x CallerScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallerScope.Descriptor instead.
func (CallerScope) EnumDescriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

// EffectClass classifies the external effect of a tool (ARCH-014). Drives
// automatic retry policy: read_only may bounded-retry; idempotent_write may
// retry only when the descriptor proves a stable strategy; non_idempotent_write
// never auto-retries after execution begins.
type EffectClass int32

const (
	EffectClass_EFFECT_CLASS_UNSPECIFIED          EffectClass = 0
	EffectClass_EFFECT_CLASS_READ_ONLY            EffectClass = 1
	EffectClass_EFFECT_CLASS_IDEMPOTENT_WRITE     EffectClass = 2
	EffectClass_EFFECT_CLASS_NON_IDEMPOTENT_WRITE EffectClass = 3
)

// Enum value maps for EffectClass.
var (
	EffectClass_name = map[int32]string{
		0: "EFFECT_CLASS_UNSPECIFIED",
		1: "EFFECT_CLASS_READ_ONLY",
		2: "EFFECT_CLASS_IDEMPOTENT_WRITE",
		3: "EFFECT_CLASS_NON_IDEMPOTENT_WRITE",
	}
	EffectClass_value = map[string]int32{
		"EFFECT_CLASS_UNSPECIFIED":          0,
		"EFFECT_CLASS_READ_ONLY":            1,
		"EFFECT_CLASS_IDEMPOTENT_WRITE":     2,
		"EFFECT_CLASS_NON_IDEMPOTENT_WRITE": 3,
	}
)

func (x EffectClass) Enum() *EffectClass {
	p := new(EffectClass)
	*p = x
	return p
}

func (x EffectClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectClass) Descriptor() protoreflect.EnumDescriptor {
	return file_iterabase_gateway_v1_gateway_proto_enumTypes[1].Descriptor()
}

func (EffectClass) Type() protoreflect.EnumType {
	return &file_iterabase_gateway_v1_gateway_proto_enumTypes[1]
}

func (x EffectClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectClass.Descriptor instead.
func (EffectClass) EnumDescriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

type CredentialScheme int32

const (
	CredentialScheme_CREDENTIAL_SCHEME_UNSPECIFIED              CredentialScheme = 0
	CredentialScheme_CREDENTIAL_SCHEME_BEARER                   CredentialScheme = 1 // a single secret value (static token/key)
	CredentialScheme_CREDENTIAL_SCHEME_OAUTH_CLIENT_CREDENTIALS CredentialScheme = 2 // client id + secret + token url + scope
)

// Enum value maps for CredentialScheme.
var (
	CredentialScheme_name = map[int32]string{
		0: "CREDENTIAL_SCHEME_UNSPECIFIED",
		1: "CREDENTIAL_SCHEME_BEARER",
		2: "CREDENTIAL_SCHEME_OAUTH_CLIENT_CREDENTIALS",
	}
	CredentialScheme_value = map[string]int32{
		"CREDENTIAL_SCHEME_UNSPECIFIED":              0,
		"CREDENTIAL_SCHEME_BEARER":                   1,
		"CREDENTIAL_SCHEME_OAUTH_CLIENT_CREDENTIALS": 2,
	}
)

func (x CredentialScheme) Enum() *CredentialScheme {
	p := new(CredentialScheme)
	*p = x
	return p
}

func (x CredentialScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_iterabase_gateway_v1_gateway_proto_enumTypes[2].Descriptor()
}

func (CredentialScheme) Type() protoreflect.EnumType {
	return &file_iterabase_gateway_v1_gateway_proto_enumTypes[2]
}

func (x CredentialScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialScheme.Descriptor instead.
func (CredentialScheme) EnumDescriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

// InvokeState is the lifecycle state of an invocation in the durable ledger
// (ARCH-014). dispatching->running->succeeded|failed|outcome_unknown. in_progress
// is the response to a duplicate caller while an invocation is still
// dispatching/running.
type InvokeState int32

const (
	InvokeState_INVOKE_STATE_UNSPECIFIED InvokeState = 0
	InvokeState_INVOKE_STATE_DISPATCHING InvokeState = 1 // ledger committed, not yet dispatched
	InvokeState_INVOKE_STATE_RUNNING     InvokeState = 2 // dispatched over the runner stream
	InvokeState_INVOKE_STATE_SUCCEEDED   InvokeState = 3
	InvokeState_INVOKE_STATE_FAILED      InvokeState = 4
	// A possible external effect occurred with no committed result and the effect
	// class disallows automatic retry. Never automatically repeated.
	InvokeState_INVOKE_STATE_OUTCOME_UNKNOWN InvokeState = 5
	// Caller-facing only: a duplicate invocation is already dispatching/running.
	InvokeState_INVOKE_STATE_IN_PROGRESS InvokeState = 6
)

// Enum value maps for InvokeState.
var (
	InvokeState_name = map[int32]string{
		0: "INVOKE_STATE_UNSPECIFIED",
		1: "INVOKE_STATE_DISPATCHING",
		2: "INVOKE_STATE_RUNNING",
		3: "INVOKE_STATE_SUCCEEDED",
		4: "INVOKE_STATE_FAILED",
		5: "INVOKE_STATE_OUTCOME_UNKNOWN",
		6: "INVOKE_STATE_IN_PROGRESS",
	}
	InvokeState_value = map[string]int32{
		"INVOKE_STATE_UNSPECIFIED":     0,
		"INVOKE_STATE_DISPATCHING":     1,
		"INVOKE_STATE_RUNNING":         2,
		"INVOKE_STATE_SUCCEEDED":       3,
		"INVOKE_STATE_FAILED":          4,
		"INVOKE_STATE_OUTCOME_UNKNOWN": 5,
		"INVOKE_STATE_IN_PROGRESS":     6,
	}
)

func (x InvokeState) Enum() *InvokeState {
	p := new(InvokeState)
	*p = x
	return p
}

func (x InvokeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvokeState) Descriptor() protoreflect.EnumDescriptor {
	return file_iterabase_gateway_v1_gateway_proto_enumTypes[3].Descriptor()
}

func (InvokeState) Type() protoreflect.EnumType {
	return &file_iterabase_gateway_v1_gateway_proto_enumTypes[3]
}

func (x InvokeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvokeState.Descriptor instead.
func (InvokeState) EnumDescriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

type Retryability int32

const (
	Retryability_RETRYABILITY_UNSPECIFIED   Retryability = 0
	Retryability_RETRYABILITY_RETRYABLE     Retryability = 1
	Retryability_RETRYABILITY_NON_RETRYABLE Retryability = 2
	Retryability_RETRYABILITY_UNKNOWN       Retryability = 3
)

// Enum value maps for Retryability.
var (
	Retryability_name = map[int32]string{
		0: "RETRYABILITY_UNSPECIFIED",
		1: "RETRYABILITY_RETRYABLE",
		2: "RETRYABILITY_NON_RETRYABLE",
		3: "RETRYABILITY_UNKNOWN",
	}
	Retryability_value = map[string]int32{
		"RETRYABILITY_UNSPECIFIED":   0,
		"RETRYABILITY_RETRYABLE":     1,
		"RETRYABILITY_NON_RETRYABLE": 2,
		"RETRYABILITY_UNKNOWN":       3,
	}
)

func (x Retryability) Enum() *Retryability {
	p := new(Retryability)
	*p = x
	return p
}

func (x Retryability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Retryability) Descriptor() protoreflect.EnumDescriptor {
	return file_iterabase_gateway_v1_gateway_proto_enumTypes[4].Descriptor()
}

func (Retryability) Type() protoreflect.EnumType {
	return &file_iterabase_gateway_v1_gateway_proto_enumTypes[4]
}

func (x Retryability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Retryability.Descriptor instead.
func (Retryability) EnumDescriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

type RunnerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RunnerMessage_Register
	//	*RunnerMessage_Heartbeat
	//	*RunnerMessage_InvokeResult
	//	*RunnerMessage_InvokeError
	Kind          isRunnerMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerMessage) Reset() {
	*x = RunnerMessage{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerMessage) ProtoMessage() {}

func (x *RunnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerMessage.ProtoReflect.Descriptor instead.
func (*RunnerMessage) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *RunnerMessage) GetKind() isRunnerMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RunnerMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *RunnerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *RunnerMessage) GetInvokeResult() *InvokeResult {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMessage_InvokeResult); ok {
			return x.InvokeResult
		}
	}
	return nil
}

func (x *RunnerMessage) GetInvokeError() *InvokeError {
	if x != nil {
		if x, ok := x.Kind.(*RunnerMessage_InvokeError); ok {
			return x.InvokeError
		}
	}
	return nil
}

type isRunnerMessage_Kind interface {
	isRunnerMessage_Kind()
}

type RunnerMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type RunnerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type RunnerMessage_InvokeResult struct {
	InvokeResult *InvokeResult `protobuf:"bytes,3,opt,name=invoke_result,json=invokeResult,proto3,oneof"` // successful or failed execution
}

type RunnerMessage_InvokeError struct {
	InvokeError *InvokeError `protobuf:"bytes,4,opt,name=invoke_error,json=invokeError,proto3,oneof"` // pre-execution / dispatch error
}

func (*RunnerMessage_Register) isRunnerMessage_Kind() {}

func (*RunnerMessage_Heartbeat) isRunnerMessage_Kind() {}

func (*RunnerMessage_InvokeResult) isRunnerMessage_Kind() {}

func (*RunnerMessage_InvokeError) isRunnerMessage_Kind() {}

// Register is the first message and may be repeated to publish additional
// immutable tool versions. Each Register carries one ToolDescriptor; a runner
// that serves several tools sends several Register messages. The runner's
// approved SPIFFE identity (URI SAN) and permitted tool namespace are verified
// by the gateway before any registration is accepted (ARCH-015); an unapproved
// identity terminates the stream with PermissionDenied.
type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   *ToolDescriptor        `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	RunnerId      string                 `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"` // stable runner instance id (within the approved namespace)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetDescriptor_() *ToolDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *Register) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

// Heartbeat renews the registration lease. Any runner message renews the lease;
// a heartbeat is needed only after an otherwise silent interval. A stale lease
// (no heartbeat within the lease timeout) excludes all of this runner's
// versions from new-attempt resolution.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // runner clock; gateway receipt is authoritative
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// InvokeResult is the terminal result of an Invoke. state=succeeded carries the
// structured result + artifact refs; state=failed carries a typed error. For a
// non_idempotent_write that lost certainty before this result could be sent,
// the gateway records outcome_unknown independently; this message reports what
// the runner knows (ARCH-014).
type InvokeResult struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InvocationId string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	State        InvokeState            `protobuf:"varint,2,opt,name=state,proto3,enum=iterabase.gateway.v1.InvokeState" json:"state,omitempty"`
	// Result payload. Inline text/JSON only (bounded by the gateway's inline
	// limit); larger outputs are artifact references resolved through the
	// artifact service (HOR-399).
	ResultJson         []byte         `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`                           // structured result (JSON), when succeeded
	ArtifactOutputRefs []*ArtifactRef `protobuf:"bytes,4,rep,name=artifact_output_refs,json=artifactOutputRefs,proto3" json:"artifact_output_refs,omitempty"` // produced artifacts
	Error              *ErrorDetail   `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                                       // when failed
	TimestampMs        int64          `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InvokeResult) Reset() {
	*x = InvokeResult{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResult) ProtoMessage() {}

func (x *InvokeResult) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResult.ProtoReflect.Descriptor instead.
func (*InvokeResult) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeResult) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *InvokeResult) GetState() InvokeState {
	if x != nil {
		return x.State
	}
	return InvokeState_INVOKE_STATE_UNSPECIFIED
}

func (x *InvokeResult) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *InvokeResult) GetArtifactOutputRefs() []*ArtifactRef {
	if x != nil {
		return x.ArtifactOutputRefs
	}
	return nil
}

func (x *InvokeResult) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *InvokeResult) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// InvokeError reports a dispatch/protocol error before execution began (e.g.
// the runner could not validate args or the pinned version is no longer
// loadable). It does NOT imply an external effect occurred; the gateway
// classifies retry per the invocation's effect class (ARCH-014).
type InvokeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeError) Reset() {
	*x = InvokeError{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeError) ProtoMessage() {}

func (x *InvokeError) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeError.ProtoReflect.Descriptor instead.
func (*InvokeError) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeError) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *InvokeError) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type RunnerControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RunnerControl_Welcome
	//	*RunnerControl_Invoke
	//	*RunnerControl_Cancel
	//	*RunnerControl_Ack
	Kind          isRunnerControl_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerControl) Reset() {
	*x = RunnerControl{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerControl) ProtoMessage() {}

func (x *RunnerControl) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerControl.ProtoReflect.Descriptor instead.
func (*RunnerControl) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *RunnerControl) GetKind() isRunnerControl_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RunnerControl) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Kind.(*RunnerControl_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *RunnerControl) GetInvoke() *Invoke {
	if x != nil {
		if x, ok := x.Kind.(*RunnerControl_Invoke); ok {
			return x.Invoke
		}
	}
	return nil
}

func (x *RunnerControl) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Kind.(*RunnerControl_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *RunnerControl) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Kind.(*RunnerControl_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isRunnerControl_Kind interface {
	isRunnerControl_Kind()
}

type RunnerControl_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type RunnerControl_Invoke struct {
	Invoke *Invoke `protobuf:"bytes,2,opt,name=invoke,proto3,oneof"`
}

type RunnerControl_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

type RunnerControl_Ack struct {
	Ack *Ack `protobuf:"bytes,4,opt,name=ack,proto3,oneof"`
}

func (*RunnerControl_Welcome) isRunnerControl_Kind() {}

func (*RunnerControl_Invoke) isRunnerControl_Kind() {}

func (*RunnerControl_Cancel) isRunnerControl_Kind() {}

func (*RunnerControl_Ack) isRunnerControl_Kind() {}

// Welcome is sent once after Register auth succeeds. A reconnection for the
// same runner_id atomically fences the previous generation; any in-flight
// invocation on the old stream is classified by the gateway (retry or
// outcome_unknown) per its effect class.
type Welcome struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion     string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	FencingGeneration   uint64                 `protobuf:"varint,2,opt,name=fencing_generation,json=fencingGeneration,proto3" json:"fencing_generation,omitempty"`
	HeartbeatIntervalMs int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	LeaseTimeoutMs      int32                  `protobuf:"varint,4,opt,name=lease_timeout_ms,json=leaseTimeoutMs,proto3" json:"lease_timeout_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *Welcome) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Welcome) GetFencingGeneration() uint64 {
	if x != nil {
		return x.FencingGeneration
	}
	return 0
}

func (x *Welcome) GetHeartbeatIntervalMs() int32 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *Welcome) GetLeaseTimeoutMs() int32 {
	if x != nil {
		return x.LeaseTimeoutMs
	}
	return 0
}

// Invoke is one tool execution dispatched over the authenticated runner stream.
// The gateway has already: resolved effective authorization, resolved
// credential bindings to values (read from K8s Secrets via the in-cluster API),
// validated arguments against the descriptor's input schema, and committed the
// invocation ledger row in the dispatching state (ARCH-014/008). The runner
// receives the pinned descriptor, arguments, the resolved CredentialContext
// (short-lived; values live only in gateway memory + this invocation), and any
// input artifact references to materialize.
type Invoke struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InvocationId      string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Descriptor_       *ToolDescriptor        `protobuf:"bytes,2,opt,name=descriptor,proto3" json:"descriptor,omitempty"`                                          // the exact pinned version/digest
	ArgumentsJson     []byte                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`               // validated JSON arguments
	IdempotencyKey    string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`            // caller-supplied; runner may propagate upstream
	ArtifactInputRefs []*ArtifactRef         `protobuf:"bytes,5,rep,name=artifact_input_refs,json=artifactInputRefs,proto3" json:"artifact_input_refs,omitempty"` // inputs to materialize (HOR-399 resolves bytes)
	CredentialContext *CredentialContext     `protobuf:"bytes,6,opt,name=credential_context,json=credentialContext,proto3" json:"credential_context,omitempty"`   // resolved credential values; never logged
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Invoke) Reset() {
	*x = Invoke{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoke) ProtoMessage() {}

func (x *Invoke) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoke.ProtoReflect.Descriptor instead.
func (*Invoke) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *Invoke) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *Invoke) GetDescriptor_() *ToolDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *Invoke) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *Invoke) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Invoke) GetArtifactInputRefs() []*ArtifactRef {
	if x != nil {
		return x.ArtifactInputRefs
	}
	return nil
}

func (x *Invoke) GetCredentialContext() *CredentialContext {
	if x != nil {
		return x.CredentialContext
	}
	return nil
}

// Cancel propagates cancellation to an in-flight invocation. Per ARCH-014 it
// cannot claim to undo an effect already started; the runner should abort
// upstream work and report the best-known state (succeeded/failed/outcome via
// InvokeResult/InvokeError). Cancel is idempotent for the matching invocation.
type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // human/audit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *Cancel) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *Cancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Ack acknowledges receipt of a Register or Heartbeat. (Invoke results are
// durable; they are not ACKed over this stream — the ledger commit is the
// durable acknowledgment.)
type Ack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Ack_Registered
	//	*Ack_Heartbeat
	Kind          isAck_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *Ack) GetKind() isAck_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Ack) GetRegistered() string {
	if x != nil {
		if x, ok := x.Kind.(*Ack_Registered); ok {
			return x.Registered
		}
	}
	return ""
}

func (x *Ack) GetHeartbeat() bool {
	if x != nil {
		if x, ok := x.Kind.(*Ack_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return false
}

type isAck_Kind interface {
	isAck_Kind()
}

type Ack_Registered struct {
	Registered string `protobuf:"bytes,1,opt,name=registered,proto3,oneof"` // the tool name+version acknowledged
}

type Ack_Heartbeat struct {
	Heartbeat bool `protobuf:"varint,2,opt,name=heartbeat,proto3,oneof"` // heartbeat acknowledged
}

func (*Ack_Registered) isAck_Kind() {}

func (*Ack_Heartbeat) isAck_Kind() {}

type DiscoverRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AttemptId         string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"` // the workflow attempt (version snapshot boundary, ARCH-007)
	CallerScope       CallerScope            `protobuf:"varint,2,opt,name=caller_scope,json=callerScope,proto3,enum=iterabase.gateway.v1.CallerScope" json:"caller_scope,omitempty"`
	CallerScopeId     string                 `protobuf:"bytes,3,opt,name=caller_scope_id,json=callerScopeId,proto3" json:"caller_scope_id,omitempty"`            // turn_id when CALLER_SCOPE_TURN, run_step_id when CALLER_SCOPE_WORKFLOW_STEP
	FencingGeneration uint64                 `protobuf:"varint,4,opt,name=fencing_generation,json=fencingGeneration,proto3" json:"fencing_generation,omitempty"` // the supervisor's current Welcome generation (HOR-249/DEC-041): the gateway binds authorization to the verified worker AND this generation, denying a fenced/old-generation caller.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *DiscoverRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *DiscoverRequest) GetCallerScope() CallerScope {
	if x != nil {
		return x.CallerScope
	}
	return CallerScope_CALLER_SCOPE_UNSPECIFIED
}

func (x *DiscoverRequest) GetCallerScopeId() string {
	if x != nil {
		return x.CallerScopeId
	}
	return ""
}

func (x *DiscoverRequest) GetFencingGeneration() uint64 {
	if x != nil {
		return x.FencingGeneration
	}
	return 0
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptors   []*ToolDescriptor      `protobuf:"bytes,1,rep,name=descriptors,proto3" json:"descriptors,omitempty"` // only the permitted, healthy, pinned versions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *DiscoverResponse) GetDescriptors() []*ToolDescriptor {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

type InvokeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AttemptId         string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	CallerScope       CallerScope            `protobuf:"varint,2,opt,name=caller_scope,json=callerScope,proto3,enum=iterabase.gateway.v1.CallerScope" json:"caller_scope,omitempty"`
	CallerScopeId     string                 `protobuf:"bytes,3,opt,name=caller_scope_id,json=callerScopeId,proto3" json:"caller_scope_id,omitempty"` // turn_id or run_step_id
	ToolCallId        string                 `protobuf:"bytes,4,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`          // the LLM/workflow tool-call identity
	ToolName          string                 `protobuf:"bytes,5,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolVersionDigest string                 `protobuf:"bytes,6,opt,name=tool_version_digest,json=toolVersionDigest,proto3" json:"tool_version_digest,omitempty"` // the pinned immutable version (ARCH-007)
	ArgumentsJson     []byte                 `protobuf:"bytes,7,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`               // business arguments only; never a secret/binding/tenant
	IdempotencyKey    string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`            // required for non_idempotent_write; recommended otherwise
	ArtifactInputRefs []*ArtifactRef         `protobuf:"bytes,9,rep,name=artifact_input_refs,json=artifactInputRefs,proto3" json:"artifact_input_refs,omitempty"`
	FencingGeneration uint64                 `protobuf:"varint,10,opt,name=fencing_generation,json=fencingGeneration,proto3" json:"fencing_generation,omitempty"` // the supervisor's current Welcome generation (HOR-249/DEC-041): bound against the active assignment.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *InvokeRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *InvokeRequest) GetCallerScope() CallerScope {
	if x != nil {
		return x.CallerScope
	}
	return CallerScope_CALLER_SCOPE_UNSPECIFIED
}

func (x *InvokeRequest) GetCallerScopeId() string {
	if x != nil {
		return x.CallerScopeId
	}
	return ""
}

func (x *InvokeRequest) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *InvokeRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *InvokeRequest) GetToolVersionDigest() string {
	if x != nil {
		return x.ToolVersionDigest
	}
	return ""
}

func (x *InvokeRequest) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *InvokeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *InvokeRequest) GetArtifactInputRefs() []*ArtifactRef {
	if x != nil {
		return x.ArtifactInputRefs
	}
	return nil
}

func (x *InvokeRequest) GetFencingGeneration() uint64 {
	if x != nil {
		return x.FencingGeneration
	}
	return 0
}

type InvokeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InvocationId       string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	State              InvokeState            `protobuf:"varint,2,opt,name=state,proto3,enum=iterabase.gateway.v1.InvokeState" json:"state,omitempty"`                // succeeded | failed | outcome_unknown | in_progress
	ResultJson         []byte                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`                           // committed result (JSON), when succeeded
	ArtifactOutputRefs []*ArtifactRef         `protobuf:"bytes,4,rep,name=artifact_output_refs,json=artifactOutputRefs,proto3" json:"artifact_output_refs,omitempty"` // committed artifact references
	Error              *ErrorDetail           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                                       // when failed/outcome_unknown
	// When state=in_progress this is the existing invocation the duplicate
	// attached to (ARCH-014: duplicates in progress attach to / report the
	// existing invocation).
	ExistingInvocationId string `protobuf:"bytes,6,opt,name=existing_invocation_id,json=existingInvocationId,proto3" json:"existing_invocation_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *InvokeResponse) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *InvokeResponse) GetState() InvokeState {
	if x != nil {
		return x.State
	}
	return InvokeState_INVOKE_STATE_UNSPECIFIED
}

func (x *InvokeResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *InvokeResponse) GetArtifactOutputRefs() []*ArtifactRef {
	if x != nil {
		return x.ArtifactOutputRefs
	}
	return nil
}

func (x *InvokeResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *InvokeResponse) GetExistingInvocationId() string {
	if x != nil {
		return x.ExistingInvocationId
	}
	return ""
}

type CancelRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InvocationId      string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Reason            string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	FencingGeneration uint64                 `protobuf:"varint,3,opt,name=fencing_generation,json=fencingGeneration,proto3" json:"fencing_generation,omitempty"` // the supervisor's current Welcome generation (HOR-249/DEC-041).
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *CancelRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *CancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelRequest) GetFencingGeneration() uint64 {
	if x != nil {
		return x.FencingGeneration
	}
	return 0
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         InvokeState            `protobuf:"varint,1,opt,name=state,proto3,enum=iterabase.gateway.v1.InvokeState" json:"state,omitempty"` // best-known state after cancel propagation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *CancelResponse) GetState() InvokeState {
	if x != nil {
		return x.State
	}
	return InvokeState_INVOKE_STATE_UNSPECIFIED
}

// ToolDescriptor is the dynamic description of one immutable tool version
// (ARCH-006). A logical tool name may have multiple immutable versions
// coexisting for pinned attempts (ARCH-007); the digest is the exact
// implementation identity retained on every audit record.
type ToolDescriptor struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // logical tool name within an approved namespace
	Version              string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // immutable version string
	Digest               string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`   // implementation content digest (the pin identity)
	Description          string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema          []byte                 `protobuf:"bytes,5,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`                                        // JSON Schema for arguments
	EffectClass          EffectClass            `protobuf:"varint,6,opt,name=effect_class,json=effectClass,proto3,enum=iterabase.gateway.v1.EffectClass" json:"effect_class,omitempty"` // drives the retry/ledger policy (ARCH-014)
	CredentialSlots      []*CredentialSlot      `protobuf:"bytes,7,rep,name=credential_slots,json=credentialSlots,proto3" json:"credential_slots,omitempty"`                            // logical slots the gateway binds to SecretRefs
	ArtifactCapabilities *ArtifactCapabilities  `protobuf:"bytes,8,opt,name=artifact_capabilities,json=artifactCapabilities,proto3" json:"artifact_capabilities,omitempty"`
	Timeout              *durationpb.Duration   `protobuf:"bytes,9,opt,name=timeout,proto3" json:"timeout,omitempty"`                                            // per-invocation execution timeout
	IdempotencyProof     *IdempotencyProof      `protobuf:"bytes,10,opt,name=idempotency_proof,json=idempotencyProof,proto3" json:"idempotency_proof,omitempty"` // required when effect_class = idempotent_write
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ToolDescriptor) Reset() {
	*x = ToolDescriptor{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDescriptor) ProtoMessage() {}

func (x *ToolDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDescriptor.ProtoReflect.Descriptor instead.
func (*ToolDescriptor) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *ToolDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ToolDescriptor) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ToolDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDescriptor) GetInputSchema() []byte {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *ToolDescriptor) GetEffectClass() EffectClass {
	if x != nil {
		return x.EffectClass
	}
	return EffectClass_EFFECT_CLASS_UNSPECIFIED
}

func (x *ToolDescriptor) GetCredentialSlots() []*CredentialSlot {
	if x != nil {
		return x.CredentialSlots
	}
	return nil
}

func (x *ToolDescriptor) GetArtifactCapabilities() *ArtifactCapabilities {
	if x != nil {
		return x.ArtifactCapabilities
	}
	return nil
}

func (x *ToolDescriptor) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ToolDescriptor) GetIdempotencyProof() *IdempotencyProof {
	if x != nil {
		return x.IdempotencyProof
	}
	return nil
}

// CredentialSlot is a logical credential declaration in a tool manifest. The
// gateway binds slots to K8s Secret references + non-secret resource
// constraints via AgentPool (ARCH-008/018). The agent supplies business
// arguments only and can never select a secret, binding, tenant, or token.
type CredentialSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                 // slot name the tool references
	Scheme        CredentialScheme       `protobuf:"varint,2,opt,name=scheme,proto3,enum=iterabase.gateway.v1.CredentialScheme" json:"scheme,omitempty"` // which Secret shape to bind
	BindingSchema []byte                 `protobuf:"bytes,3,opt,name=binding_schema,json=bindingSchema,proto3" json:"binding_schema,omitempty"`          // JSON Schema for the binding value (non-secret constraints)
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialSlot) Reset() {
	*x = CredentialSlot{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialSlot) ProtoMessage() {}

func (x *CredentialSlot) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialSlot.ProtoReflect.Descriptor instead.
func (*CredentialSlot) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *CredentialSlot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CredentialSlot) GetScheme() CredentialScheme {
	if x != nil {
		return x.Scheme
	}
	return CredentialScheme_CREDENTIAL_SCHEME_UNSPECIFIED
}

func (x *CredentialSlot) GetBindingSchema() []byte {
	if x != nil {
		return x.BindingSchema
	}
	return nil
}

func (x *CredentialSlot) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

// ArtifactCapabilities declares what the tool can read/produce as artifacts
// (ARCH-013). Large inputs/outputs are artifact references, not inline bytes;
// the gateway stores refs in the ledger and the artifact service (HOR-399)
// owns immutable bytes.
type ArtifactCapabilities struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReadsArtifacts    bool                   `protobuf:"varint,1,opt,name=reads_artifacts,json=readsArtifacts,proto3" json:"reads_artifacts,omitempty"`
	WritesArtifacts   bool                   `protobuf:"varint,2,opt,name=writes_artifacts,json=writesArtifacts,proto3" json:"writes_artifacts,omitempty"`
	AcceptedMimeTypes []string               `protobuf:"bytes,3,rep,name=accepted_mime_types,json=acceptedMimeTypes,proto3" json:"accepted_mime_types,omitempty"` // for inputs the tool can materialize
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ArtifactCapabilities) Reset() {
	*x = ArtifactCapabilities{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactCapabilities) ProtoMessage() {}

func (x *ArtifactCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactCapabilities.ProtoReflect.Descriptor instead.
func (*ArtifactCapabilities) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{18}
}

func (x *ArtifactCapabilities) GetReadsArtifacts() bool {
	if x != nil {
		return x.ReadsArtifacts
	}
	return false
}

func (x *ArtifactCapabilities) GetWritesArtifacts() bool {
	if x != nil {
		return x.WritesArtifacts
	}
	return false
}

func (x *ArtifactCapabilities) GetAcceptedMimeTypes() []string {
	if x != nil {
		return x.AcceptedMimeTypes
	}
	return nil
}

// IdempotencyProof is required for effect_class = idempotent_write. It declares
// the stable strategy that makes a retry safe: an upstream idempotency key the
// runner propagates, and/or a deterministic resource identity. The gateway
// allows automatic retry only when this proof is present and the runner reports
// a retryable failure (ARCH-014).
type IdempotencyProof struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Strategy          string                 `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`                                              // upstream_key | deterministic_resource_id | ...
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                        // human-readable explanation
	UpstreamKeyHeader string                 `protobuf:"bytes,3,opt,name=upstream_key_header,json=upstreamKeyHeader,proto3" json:"upstream_key_header,omitempty"` // header/param the runner propagates, when applicable
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IdempotencyProof) Reset() {
	*x = IdempotencyProof{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyProof) ProtoMessage() {}

func (x *IdempotencyProof) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyProof.ProtoReflect.Descriptor instead.
func (*IdempotencyProof) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{19}
}

func (x *IdempotencyProof) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *IdempotencyProof) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IdempotencyProof) GetUpstreamKeyHeader() string {
	if x != nil {
		return x.UpstreamKeyHeader
	}
	return ""
}

// CredentialContext is the resolved credential-aware invocation context handed
// to trusted tool code (ARCH-008). Values live only in gateway memory + the
// runner's per-invocation context; they NEVER enter Postgres, logs, tool
// results, or the sandbox. Each slot the descriptor declared is resolved here.
type CredentialContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         map[string]*Credential `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // slot name -> resolved credential
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialContext) Reset() {
	*x = CredentialContext{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialContext) ProtoMessage() {}

func (x *CredentialContext) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialContext.ProtoReflect.Descriptor instead.
func (*CredentialContext) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{20}
}

func (x *CredentialContext) GetSlots() map[string]*Credential {
	if x != nil {
		return x.Slots
	}
	return nil
}

// Credential is one resolved credential value. The scheme selects which fields
// apply, mirroring CredentialSlot.scheme.
type Credential struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Scheme            CredentialScheme       `protobuf:"varint,1,opt,name=scheme,proto3,enum=iterabase.gateway.v1.CredentialScheme" json:"scheme,omitempty"`
	BearerValue       string                 `protobuf:"bytes,2,opt,name=bearer_value,json=bearerValue,proto3" json:"bearer_value,omitempty"`                     // CREDENTIAL_SCHEME_BEARER
	OauthClientId     string                 `protobuf:"bytes,3,opt,name=oauth_client_id,json=oauthClientId,proto3" json:"oauth_client_id,omitempty"`             // CREDENTIAL_SCHEME_OAUTH_CLIENT_CREDENTIALS
	OauthClientSecret string                 `protobuf:"bytes,4,opt,name=oauth_client_secret,json=oauthClientSecret,proto3" json:"oauth_client_secret,omitempty"` // CREDENTIAL_SCHEME_OAUTH_CLIENT_CREDENTIALS
	OauthTokenUrl     string                 `protobuf:"bytes,5,opt,name=oauth_token_url,json=oauthTokenUrl,proto3" json:"oauth_token_url,omitempty"`             // CREDENTIAL_SCHEME_OAUTH_CLIENT_CREDENTIALS
	OauthScope        string                 `protobuf:"bytes,6,opt,name=oauth_scope,json=oauthScope,proto3" json:"oauth_scope,omitempty"`                        // CREDENTIAL_SCHEME_OAUTH_CLIENT_CREDENTIALS
	// Non-secret resource constraints bound to this slot (e.g. tenant, site,
	// mailbox). Never a secret value.
	ResourceConstraintsJson []byte `protobuf:"bytes,7,opt,name=resource_constraints_json,json=resourceConstraintsJson,proto3" json:"resource_constraints_json,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{21}
}

func (x *Credential) GetScheme() CredentialScheme {
	if x != nil {
		return x.Scheme
	}
	return CredentialScheme_CREDENTIAL_SCHEME_UNSPECIFIED
}

func (x *Credential) GetBearerValue() string {
	if x != nil {
		return x.BearerValue
	}
	return ""
}

func (x *Credential) GetOauthClientId() string {
	if x != nil {
		return x.OauthClientId
	}
	return ""
}

func (x *Credential) GetOauthClientSecret() string {
	if x != nil {
		return x.OauthClientSecret
	}
	return ""
}

func (x *Credential) GetOauthTokenUrl() string {
	if x != nil {
		return x.OauthTokenUrl
	}
	return ""
}

func (x *Credential) GetOauthScope() string {
	if x != nil {
		return x.OauthScope
	}
	return ""
}

func (x *Credential) GetResourceConstraintsJson() []byte {
	if x != nil {
		return x.ResourceConstraintsJson
	}
	return nil
}

// ArtifactRef references an immutable artifact owned by the artifact service
// (HOR-399). The gateway carries refs, not bytes; the trusted supervisor
// materializes only authorized input refs into the session workspace.
type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"` // durable artifact id (HOR-399)
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"` // content digest for verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{22}
}

func (x *ArtifactRef) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactRef) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ArtifactRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactRef) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// A stable error envelope (mirrors the harness ErrorDetail). details_json
// carries source-specific diagnostics; it MUST NOT contain secret values.
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryability  Retryability           `protobuf:"varint,3,opt,name=retryability,proto3,enum=iterabase.gateway.v1.Retryability" json:"retryability,omitempty"`
	DetailsJson   string                 `protobuf:"bytes,4,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_gateway_v1_gateway_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_iterabase_gateway_v1_gateway_proto_rawDescGZIP(), []int{23}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetRetryability() Retryability {
	if x != nil {
		return x.Retryability
	}
	return Retryability_RETRYABILITY_UNSPECIFIED
}

func (x *ErrorDetail) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

var File_iterabase_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_iterabase_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\"iterabase/gateway/v1/gateway.proto\x12\x14iterabase.gateway.v1\x1a\x1egoogle/protobuf/duration.proto\"\xa9\x02\n" +
	"\rRunnerMessage\x12<\n" +
	"\bregister\x18\x01 \x01(\v2\x1e.iterabase.gateway.v1.RegisterH\x00R\bregister\x12?\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1f.iterabase.gateway.v1.HeartbeatH\x00R\theartbeat\x12I\n" +
	"\rinvoke_result\x18\x03 \x01(\v2\".iterabase.gateway.v1.InvokeResultH\x00R\finvokeResult\x12F\n" +
	"\finvoke_error\x18\x04 \x01(\v2!.iterabase.gateway.v1.InvokeErrorH\x00R\vinvokeErrorB\x06\n" +
	"\x04kind\"m\n" +
	"\bRegister\x12D\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\v2$.iterabase.gateway.v1.ToolDescriptorR\n" +
	"descriptor\x12\x1b\n" +
	"\trunner_id\x18\x02 \x01(\tR\brunnerId\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"\xbe\x02\n" +
	"\fInvokeResult\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x127\n" +
	"\x05state\x18\x02 \x01(\x0e2!.iterabase.gateway.v1.InvokeStateR\x05state\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\fR\n" +
	"resultJson\x12S\n" +
	"\x14artifact_output_refs\x18\x04 \x03(\v2!.iterabase.gateway.v1.ArtifactRefR\x12artifactOutputRefs\x127\n" +
	"\x05error\x18\x05 \x01(\v2!.iterabase.gateway.v1.ErrorDetailR\x05error\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\"k\n" +
	"\vInvokeError\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x127\n" +
	"\x05error\x18\x02 \x01(\v2!.iterabase.gateway.v1.ErrorDetailR\x05error\"\xf1\x01\n" +
	"\rRunnerControl\x129\n" +
	"\awelcome\x18\x01 \x01(\v2\x1d.iterabase.gateway.v1.WelcomeH\x00R\awelcome\x126\n" +
	"\x06invoke\x18\x02 \x01(\v2\x1c.iterabase.gateway.v1.InvokeH\x00R\x06invoke\x126\n" +
	"\x06cancel\x18\x03 \x01(\v2\x1c.iterabase.gateway.v1.CancelH\x00R\x06cancel\x12-\n" +
	"\x03ack\x18\x04 \x01(\v2\x19.iterabase.gateway.v1.AckH\x00R\x03ackB\x06\n" +
	"\x04kind\"\xc1\x01\n" +
	"\aWelcome\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12-\n" +
	"\x12fencing_generation\x18\x02 \x01(\x04R\x11fencingGeneration\x122\n" +
	"\x15heartbeat_interval_ms\x18\x03 \x01(\x05R\x13heartbeatIntervalMs\x12(\n" +
	"\x10lease_timeout_ms\x18\x04 \x01(\x05R\x0eleaseTimeoutMs\"\xee\x02\n" +
	"\x06Invoke\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12D\n" +
	"\n" +
	"descriptor\x18\x02 \x01(\v2$.iterabase.gateway.v1.ToolDescriptorR\n" +
	"descriptor\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\fR\rargumentsJson\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12Q\n" +
	"\x13artifact_input_refs\x18\x05 \x03(\v2!.iterabase.gateway.v1.ArtifactRefR\x11artifactInputRefs\x12V\n" +
	"\x12credential_context\x18\x06 \x01(\v2'.iterabase.gateway.v1.CredentialContextR\x11credentialContext\"E\n" +
	"\x06Cancel\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"O\n" +
	"\x03Ack\x12 \n" +
	"\n" +
	"registered\x18\x01 \x01(\tH\x00R\n" +
	"registered\x12\x1e\n" +
	"\theartbeat\x18\x02 \x01(\bH\x00R\theartbeatB\x06\n" +
	"\x04kind\"\xcd\x01\n" +
	"\x0fDiscoverRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12D\n" +
	"\fcaller_scope\x18\x02 \x01(\x0e2!.iterabase.gateway.v1.CallerScopeR\vcallerScope\x12&\n" +
	"\x0fcaller_scope_id\x18\x03 \x01(\tR\rcallerScopeId\x12-\n" +
	"\x12fencing_generation\x18\x04 \x01(\x04R\x11fencingGeneration\"Z\n" +
	"\x10DiscoverResponse\x12F\n" +
	"\vdescriptors\x18\x01 \x03(\v2$.iterabase.gateway.v1.ToolDescriptorR\vdescriptors\"\xdd\x03\n" +
	"\rInvokeRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12D\n" +
	"\fcaller_scope\x18\x02 \x01(\x0e2!.iterabase.gateway.v1.CallerScopeR\vcallerScope\x12&\n" +
	"\x0fcaller_scope_id\x18\x03 \x01(\tR\rcallerScopeId\x12 \n" +
	"\ftool_call_id\x18\x04 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x05 \x01(\tR\btoolName\x12.\n" +
	"\x13tool_version_digest\x18\x06 \x01(\tR\x11toolVersionDigest\x12%\n" +
	"\x0earguments_json\x18\a \x01(\fR\rargumentsJson\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x12Q\n" +
	"\x13artifact_input_refs\x18\t \x03(\v2!.iterabase.gateway.v1.ArtifactRefR\x11artifactInputRefs\x12-\n" +
	"\x12fencing_generation\x18\n" +
	" \x01(\x04R\x11fencingGeneration\"\xd3\x02\n" +
	"\x0eInvokeResponse\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x127\n" +
	"\x05state\x18\x02 \x01(\x0e2!.iterabase.gateway.v1.InvokeStateR\x05state\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\fR\n" +
	"resultJson\x12S\n" +
	"\x14artifact_output_refs\x18\x04 \x03(\v2!.iterabase.gateway.v1.ArtifactRefR\x12artifactOutputRefs\x127\n" +
	"\x05error\x18\x05 \x01(\v2!.iterabase.gateway.v1.ErrorDetailR\x05error\x124\n" +
	"\x16existing_invocation_id\x18\x06 \x01(\tR\x14existingInvocationId\"{\n" +
	"\rCancelRequest\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12-\n" +
	"\x12fencing_generation\x18\x03 \x01(\x04R\x11fencingGeneration\"I\n" +
	"\x0eCancelResponse\x127\n" +
	"\x05state\x18\x01 \x01(\x0e2!.iterabase.gateway.v1.InvokeStateR\x05state\"\x9d\x04\n" +
	"\x0eToolDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x05 \x01(\fR\vinputSchema\x12D\n" +
	"\feffect_class\x18\x06 \x01(\x0e2!.iterabase.gateway.v1.EffectClassR\veffectClass\x12O\n" +
	"\x10credential_slots\x18\a \x03(\v2$.iterabase.gateway.v1.CredentialSlotR\x0fcredentialSlots\x12_\n" +
	"\x15artifact_capabilities\x18\b \x01(\v2*.iterabase.gateway.v1.ArtifactCapabilitiesR\x14artifactCapabilities\x123\n" +
	"\atimeout\x18\t \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12S\n" +
	"\x11idempotency_proof\x18\n" +
	" \x01(\v2&.iterabase.gateway.v1.IdempotencyProofR\x10idempotencyProof\"\xa7\x01\n" +
	"\x0eCredentialSlot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\x06scheme\x18\x02 \x01(\x0e2&.iterabase.gateway.v1.CredentialSchemeR\x06scheme\x12%\n" +
	"\x0ebinding_schema\x18\x03 \x01(\fR\rbindingSchema\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\"\x9a\x01\n" +
	"\x14ArtifactCapabilities\x12'\n" +
	"\x0freads_artifacts\x18\x01 \x01(\bR\x0ereadsArtifacts\x12)\n" +
	"\x10writes_artifacts\x18\x02 \x01(\bR\x0fwritesArtifacts\x12.\n" +
	"\x13accepted_mime_types\x18\x03 \x03(\tR\x11acceptedMimeTypes\"\x80\x01\n" +
	"\x10IdempotencyProof\x12\x1a\n" +
	"\bstrategy\x18\x01 \x01(\tR\bstrategy\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12.\n" +
	"\x13upstream_key_header\x18\x03 \x01(\tR\x11upstreamKeyHeader\"\xb9\x01\n" +
	"\x11CredentialContext\x12H\n" +
	"\x05slots\x18\x01 \x03(\v22.iterabase.gateway.v1.CredentialContext.SlotsEntryR\x05slots\x1aZ\n" +
	"\n" +
	"SlotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .iterabase.gateway.v1.CredentialR\x05value:\x028\x01\"\xcc\x02\n" +
	"\n" +
	"Credential\x12>\n" +
	"\x06scheme\x18\x01 \x01(\x0e2&.iterabase.gateway.v1.CredentialSchemeR\x06scheme\x12!\n" +
	"\fbearer_value\x18\x02 \x01(\tR\vbearerValue\x12&\n" +
	"\x0foauth_client_id\x18\x03 \x01(\tR\roauthClientId\x12.\n" +
	"\x13oauth_client_secret\x18\x04 \x01(\tR\x11oauthClientSecret\x12&\n" +
	"\x0foauth_token_url\x18\x05 \x01(\tR\roauthTokenUrl\x12\x1f\n" +
	"\voauth_scope\x18\x06 \x01(\tR\n" +
	"oauthScope\x12:\n" +
	"\x19resource_constraints_json\x18\a \x01(\fR\x17resourceConstraintsJson\"\x82\x01\n" +
	"\vArtifactRef\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"\xa6\x01\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\fretryability\x18\x03 \x01(\x0e2\".iterabase.gateway.v1.RetryabilityR\fretryability\x12!\n" +
	"\fdetails_json\x18\x04 \x01(\tR\vdetailsJson*b\n" +
	"\vCallerScope\x12\x1c\n" +
	"\x18CALLER_SCOPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CALLER_SCOPE_TURN\x10\x01\x12\x1e\n" +
	"\x1aCALLER_SCOPE_WORKFLOW_STEP\x10\x02*\x91\x01\n" +
	"\vEffectClass\x12\x1c\n" +
	"\x18EFFECT_CLASS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EFFECT_CLASS_READ_ONLY\x10\x01\x12!\n" +
	"\x1dEFFECT_CLASS_IDEMPOTENT_WRITE\x10\x02\x12%\n" +
	"!EFFECT_CLASS_NON_IDEMPOTENT_WRITE\x10\x03*\x83\x01\n" +
	"\x10CredentialScheme\x12!\n" +
	"\x1dCREDENTIAL_SCHEME_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CREDENTIAL_SCHEME_BEARER\x10\x01\x12.\n" +
	"*CREDENTIAL_SCHEME_OAUTH_CLIENT_CREDENTIALS\x10\x02*\xd8\x01\n" +
	"\vInvokeState\x12\x1c\n" +
	"\x18INVOKE_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18INVOKE_STATE_DISPATCHING\x10\x01\x12\x18\n" +
	"\x14INVOKE_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16INVOKE_STATE_SUCCEEDED\x10\x03\x12\x17\n" +
	"\x13INVOKE_STATE_FAILED\x10\x04\x12 \n" +
	"\x1cINVOKE_STATE_OUTCOME_UNKNOWN\x10\x05\x12\x1c\n" +
	"\x18INVOKE_STATE_IN_PROGRESS\x10\x06*\x82\x01\n" +
	"\fRetryability\x12\x1c\n" +
	"\x18RETRYABILITY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RETRYABILITY_RETRYABLE\x10\x01\x12\x1e\n" +
	"\x1aRETRYABILITY_NON_RETRYABLE\x10\x02\x12\x18\n" +
	"\x14RETRYABILITY_UNKNOWN\x10\x032o\n" +
	"\rRunnerService\x12^\n" +
	"\x0eRegisterRunner\x12#.iterabase.gateway.v1.RunnerMessage\x1a#.iterabase.gateway.v1.RunnerControl(\x010\x012\xb1\x02\n" +
	"\x0eGatewayService\x12g\n" +
	"\x16DiscoverEffectiveTools\x12%.iterabase.gateway.v1.DiscoverRequest\x1a&.iterabase.gateway.v1.DiscoverResponse\x12W\n" +
	"\n" +
	"InvokeTool\x12#.iterabase.gateway.v1.InvokeRequest\x1a$.iterabase.gateway.v1.InvokeResponse\x12]\n" +
	"\x10CancelInvocation\x12#.iterabase.gateway.v1.CancelRequest\x1a$.iterabase.gateway.v1.CancelResponseB\xf6\x01\n" +
	"\x18com.iterabase.gateway.v1B\fGatewayProtoP\x01ZZgithub.com/nunocgoncalves/control-plane/internal/gatewayrpc/iterabase/gateway/v1;gatewayv1\xa2\x02\x03IGX\xaa\x02\x14Iterabase.Gateway.V1\xca\x02\x14Iterabase\\Gateway\\V1\xe2\x02 Iterabase\\Gateway\\V1\\GPBMetadata\xea\x02\x16Iterabase::Gateway::V1b\x06proto3"

var (
	file_iterabase_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_iterabase_gateway_v1_gateway_proto_rawDescData []byte
)

func file_iterabase_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_iterabase_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_iterabase_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iterabase_gateway_v1_gateway_proto_rawDesc), len(file_iterabase_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_iterabase_gateway_v1_gateway_proto_rawDescData
}

var file_iterabase_gateway_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_iterabase_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_iterabase_gateway_v1_gateway_proto_goTypes = []any{
	(CallerScope)(0),             // 0: iterabase.gateway.v1.CallerScope
	(EffectClass)(0),             // 1: iterabase.gateway.v1.EffectClass
	(CredentialScheme)(0),        // 2: iterabase.gateway.v1.CredentialScheme
	(InvokeState)(0),             // 3: iterabase.gateway.v1.InvokeState
	(Retryability)(0),            // 4: iterabase.gateway.v1.Retryability
	(*RunnerMessage)(nil),        // 5: iterabase.gateway.v1.RunnerMessage
	(*Register)(nil),             // 6: iterabase.gateway.v1.Register
	(*Heartbeat)(nil),            // 7: iterabase.gateway.v1.Heartbeat
	(*InvokeResult)(nil),         // 8: iterabase.gateway.v1.InvokeResult
	(*InvokeError)(nil),          // 9: iterabase.gateway.v1.InvokeError
	(*RunnerControl)(nil),        // 10: iterabase.gateway.v1.RunnerControl
	(*Welcome)(nil),              // 11: iterabase.gateway.v1.Welcome
	(*Invoke)(nil),               // 12: iterabase.gateway.v1.Invoke
	(*Cancel)(nil),               // 13: iterabase.gateway.v1.Cancel
	(*Ack)(nil),                  // 14: iterabase.gateway.v1.Ack
	(*DiscoverRequest)(nil),      // 15: iterabase.gateway.v1.DiscoverRequest
	(*DiscoverResponse)(nil),     // 16: iterabase.gateway.v1.DiscoverResponse
	(*InvokeRequest)(nil),        // 17: iterabase.gateway.v1.InvokeRequest
	(*InvokeResponse)(nil),       // 18: iterabase.gateway.v1.InvokeResponse
	(*CancelRequest)(nil),        // 19: iterabase.gateway.v1.CancelRequest
	(*CancelResponse)(nil),       // 20: iterabase.gateway.v1.CancelResponse
	(*ToolDescriptor)(nil),       // 21: iterabase.gateway.v1.ToolDescriptor
	(*CredentialSlot)(nil),       // 22: iterabase.gateway.v1.CredentialSlot
	(*ArtifactCapabilities)(nil), // 23: iterabase.gateway.v1.ArtifactCapabilities
	(*IdempotencyProof)(nil),     // 24: iterabase.gateway.v1.IdempotencyProof
	(*CredentialContext)(nil),    // 25: iterabase.gateway.v1.CredentialContext
	(*Credential)(nil),           // 26: iterabase.gateway.v1.Credential
	(*ArtifactRef)(nil),          // 27: iterabase.gateway.v1.ArtifactRef
	(*ErrorDetail)(nil),          // 28: iterabase.gateway.v1.ErrorDetail
	nil,                          // 29: iterabase.gateway.v1.CredentialContext.SlotsEntry
	(*durationpb.Duration)(nil),  // 30: google.protobuf.Duration
}
var file_iterabase_gateway_v1_gateway_proto_depIdxs = []int32{
	6,  // 0: iterabase.gateway.v1.RunnerMessage.register:type_name -> iterabase.gateway.v1.Register
	7,  // 1: iterabase.gateway.v1.RunnerMessage.heartbeat:type_name -> iterabase.gateway.v1.Heartbeat
	8,  // 2: iterabase.gateway.v1.RunnerMessage.invoke_result:type_name -> iterabase.gateway.v1.InvokeResult
	9,  // 3: iterabase.gateway.v1.RunnerMessage.invoke_error:type_name -> iterabase.gateway.v1.InvokeError
	21, // 4: iterabase.gateway.v1.Register.descriptor:type_name -> iterabase.gateway.v1.ToolDescriptor
	3,  // 5: iterabase.gateway.v1.InvokeResult.state:type_name -> iterabase.gateway.v1.InvokeState
	27, // 6: iterabase.gateway.v1.InvokeResult.artifact_output_refs:type_name -> iterabase.gateway.v1.ArtifactRef
	28, // 7: iterabase.gateway.v1.InvokeResult.error:type_name -> iterabase.gateway.v1.ErrorDetail
	28, // 8: iterabase.gateway.v1.InvokeError.error:type_name -> iterabase.gateway.v1.ErrorDetail
	11, // 9: iterabase.gateway.v1.RunnerControl.welcome:type_name -> iterabase.gateway.v1.Welcome
	12, // 10: iterabase.gateway.v1.RunnerControl.invoke:type_name -> iterabase.gateway.v1.Invoke
	13, // 11: iterabase.gateway.v1.RunnerControl.cancel:type_name -> iterabase.gateway.v1.Cancel
	14, // 12: iterabase.gateway.v1.RunnerControl.ack:type_name -> iterabase.gateway.v1.Ack
	21, // 13: iterabase.gateway.v1.Invoke.descriptor:type_name -> iterabase.gateway.v1.ToolDescriptor
	27, // 14: iterabase.gateway.v1.Invoke.artifact_input_refs:type_name -> iterabase.gateway.v1.ArtifactRef
	25, // 15: iterabase.gateway.v1.Invoke.credential_context:type_name -> iterabase.gateway.v1.CredentialContext
	0,  // 16: iterabase.gateway.v1.DiscoverRequest.caller_scope:type_name -> iterabase.gateway.v1.CallerScope
	21, // 17: iterabase.gateway.v1.DiscoverResponse.descriptors:type_name -> iterabase.gateway.v1.ToolDescriptor
	0,  // 18: iterabase.gateway.v1.InvokeRequest.caller_scope:type_name -> iterabase.gateway.v1.CallerScope
	27, // 19: iterabase.gateway.v1.InvokeRequest.artifact_input_refs:type_name -> iterabase.gateway.v1.ArtifactRef
	3,  // 20: iterabase.gateway.v1.InvokeResponse.state:type_name -> iterabase.gateway.v1.InvokeState
	27, // 21: iterabase.gateway.v1.InvokeResponse.artifact_output_refs:type_name -> iterabase.gateway.v1.ArtifactRef
	28, // 22: iterabase.gateway.v1.InvokeResponse.error:type_name -> iterabase.gateway.v1.ErrorDetail
	3,  // 23: iterabase.gateway.v1.CancelResponse.state:type_name -> iterabase.gateway.v1.InvokeState
	1,  // 24: iterabase.gateway.v1.ToolDescriptor.effect_class:type_name -> iterabase.gateway.v1.EffectClass
	22, // 25: iterabase.gateway.v1.ToolDescriptor.credential_slots:type_name -> iterabase.gateway.v1.CredentialSlot
	23, // 26: iterabase.gateway.v1.ToolDescriptor.artifact_capabilities:type_name -> iterabase.gateway.v1.ArtifactCapabilities
	30, // 27: iterabase.gateway.v1.ToolDescriptor.timeout:type_name -> google.protobuf.Duration
	24, // 28: iterabase.gateway.v1.ToolDescriptor.idempotency_proof:type_name -> iterabase.gateway.v1.IdempotencyProof
	2,  // 29: iterabase.gateway.v1.CredentialSlot.scheme:type_name -> iterabase.gateway.v1.CredentialScheme
	29, // 30: iterabase.gateway.v1.CredentialContext.slots:type_name -> iterabase.gateway.v1.CredentialContext.SlotsEntry
	2,  // 31: iterabase.gateway.v1.Credential.scheme:type_name -> iterabase.gateway.v1.CredentialScheme
	4,  // 32: iterabase.gateway.v1.ErrorDetail.retryability:type_name -> iterabase.gateway.v1.Retryability
	26, // 33: iterabase.gateway.v1.CredentialContext.SlotsEntry.value:type_name -> iterabase.gateway.v1.Credential
	5,  // 34: iterabase.gateway.v1.RunnerService.RegisterRunner:input_type -> iterabase.gateway.v1.RunnerMessage
	15, // 35: iterabase.gateway.v1.GatewayService.DiscoverEffectiveTools:input_type -> iterabase.gateway.v1.DiscoverRequest
	17, // 36: iterabase.gateway.v1.GatewayService.InvokeTool:input_type -> iterabase.gateway.v1.InvokeRequest
	19, // 37: iterabase.gateway.v1.GatewayService.CancelInvocation:input_type -> iterabase.gateway.v1.CancelRequest
	10, // 38: iterabase.gateway.v1.RunnerService.RegisterRunner:output_type -> iterabase.gateway.v1.RunnerControl
	16, // 39: iterabase.gateway.v1.GatewayService.DiscoverEffectiveTools:output_type -> iterabase.gateway.v1.DiscoverResponse
	18, // 40: iterabase.gateway.v1.GatewayService.InvokeTool:output_type -> iterabase.gateway.v1.InvokeResponse
	20, // 41: iterabase.gateway.v1.GatewayService.CancelInvocation:output_type -> iterabase.gateway.v1.CancelResponse
	38, // [38:42] is the sub-list for method output_type
	34, // [34:38] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_iterabase_gateway_v1_gateway_proto_init() }
func file_iterabase_gateway_v1_gateway_proto_init() {
	if File_iterabase_gateway_v1_gateway_proto != nil {
		return
	}
	file_iterabase_gateway_v1_gateway_proto_msgTypes[0].OneofWrappers = []any{
		(*RunnerMessage_Register)(nil),
		(*RunnerMessage_Heartbeat)(nil),
		(*RunnerMessage_InvokeResult)(nil),
		(*RunnerMessage_InvokeError)(nil),
	}
	file_iterabase_gateway_v1_gateway_proto_msgTypes[5].OneofWrappers = []any{
		(*RunnerControl_Welcome)(nil),
		(*RunnerControl_Invoke)(nil),
		(*RunnerControl_Cancel)(nil),
		(*RunnerControl_Ack)(nil),
	}
	file_iterabase_gateway_v1_gateway_proto_msgTypes[9].OneofWrappers = []any{
		(*Ack_Registered)(nil),
		(*Ack_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iterabase_gateway_v1_gateway_proto_rawDesc), len(file_iterabase_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_iterabase_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_iterabase_gateway_v1_gateway_proto_depIdxs,
		EnumInfos:         file_iterabase_gateway_v1_gateway_proto_enumTypes,
		MessageInfos:      file_iterabase_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_iterabase_gateway_v1_gateway_proto = out.File
	file_iterabase_gateway_v1_gateway_proto_goTypes = nil
	file_iterabase_gateway_v1_gateway_proto_depIdxs = nil
}
