---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.iterabase.com
  resources:
  - identitymappings
  - modelbackends
  - models
  - permissionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.iterabase.com
  resources:
  - identitymappings/finalizers
  - modelbackends/finalizers
  - models/finalizers
  - permissionpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - platform.iterabase.com
  resources:
  - identitymappings/status
  - modelbackends/status
  - models/status
  - permissionpolicies/status
  verbs:
  - get
  - patch
  - update
