// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: iterabase/harness/v1/harness.proto

package harnessv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nunocgoncalves/control-plane/internal/harnessrpc/iterabase/harness/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HarnessName is the fully-qualified name of the Harness service.
	HarnessName = "iterabase.harness.v1.Harness"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HarnessWorkProcedure is the fully-qualified name of the Harness's Work RPC.
	HarnessWorkProcedure = "/iterabase.harness.v1.Harness/Work"
)

// HarnessClient is a client for the iterabase.harness.v1.Harness service.
type HarnessClient interface {
	// Work is the one long-lived bidi stream per worker. Worker->CP: Hello,
	// Ready, Heartbeat, TurnEvent (durable), TokenDelta (ephemeral). CP->worker:
	// Welcome, AssignTurn, AbortTurn, EventAck, SessionEnd.
	Work(context.Context) *connect.BidiStreamForClient[v1.WorkerMessage, v1.ControlMessage]
}

// NewHarnessClient constructs a client for the iterabase.harness.v1.Harness service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHarnessClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HarnessClient {
	baseURL = strings.TrimRight(baseURL, "/")
	harnessMethods := v1.File_iterabase_harness_v1_harness_proto.Services().ByName("Harness").Methods()
	return &harnessClient{
		work: connect.NewClient[v1.WorkerMessage, v1.ControlMessage](
			httpClient,
			baseURL+HarnessWorkProcedure,
			connect.WithSchema(harnessMethods.ByName("Work")),
			connect.WithClientOptions(opts...),
		),
	}
}

// harnessClient implements HarnessClient.
type harnessClient struct {
	work *connect.Client[v1.WorkerMessage, v1.ControlMessage]
}

// Work calls iterabase.harness.v1.Harness.Work.
func (c *harnessClient) Work(ctx context.Context) *connect.BidiStreamForClient[v1.WorkerMessage, v1.ControlMessage] {
	return c.work.CallBidiStream(ctx)
}

// HarnessHandler is an implementation of the iterabase.harness.v1.Harness service.
type HarnessHandler interface {
	// Work is the one long-lived bidi stream per worker. Worker->CP: Hello,
	// Ready, Heartbeat, TurnEvent (durable), TokenDelta (ephemeral). CP->worker:
	// Welcome, AssignTurn, AbortTurn, EventAck, SessionEnd.
	Work(context.Context, *connect.BidiStream[v1.WorkerMessage, v1.ControlMessage]) error
}

// NewHarnessHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHarnessHandler(svc HarnessHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	harnessMethods := v1.File_iterabase_harness_v1_harness_proto.Services().ByName("Harness").Methods()
	harnessWorkHandler := connect.NewBidiStreamHandler(
		HarnessWorkProcedure,
		svc.Work,
		connect.WithSchema(harnessMethods.ByName("Work")),
		connect.WithHandlerOptions(opts...),
	)
	return "/iterabase.harness.v1.Harness/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HarnessWorkProcedure:
			harnessWorkHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHarnessHandler returns CodeUnimplemented from all methods.
type UnimplementedHarnessHandler struct{}

func (UnimplementedHarnessHandler) Work(context.Context, *connect.BidiStream[v1.WorkerMessage, v1.ControlMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("iterabase.harness.v1.Harness.Work is not implemented"))
}
