//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPool) DeepCopyInto(out *AgentPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPool.
func (in *AgentPool) DeepCopy() *AgentPool {
	if in == nil {
		return nil
	}
	out := new(AgentPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPoolList) DeepCopyInto(out *AgentPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPoolList.
func (in *AgentPoolList) DeepCopy() *AgentPoolList {
	if in == nil {
		return nil
	}
	out := new(AgentPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPoolSpec) DeepCopyInto(out *AgentPoolSpec) {
	*out = *in
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.Identity = in.Identity
	in.Sandbox.DeepCopyInto(&out.Sandbox)
	in.Gateways.DeepCopyInto(&out.Gateways)
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
	if in.GatewayGrants != nil {
		in, out := &in.GatewayGrants, &out.GatewayGrants
		*out = make([]GatewayGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CredentialBindings != nil {
		in, out := &in.CredentialBindings, &out.CredentialBindings
		*out = make([]CredentialBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PiDirs != nil {
		in, out := &in.PiDirs, &out.PiDirs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Probe = in.Probe
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPoolSpec.
func (in *AgentPoolSpec) DeepCopy() *AgentPoolSpec {
	if in == nil {
		return nil
	}
	out := new(AgentPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPoolStatus) DeepCopyInto(out *AgentPoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPoolStatus.
func (in *AgentPoolStatus) DeepCopy() *AgentPoolStatus {
	if in == nil {
		return nil
	}
	out := new(AgentPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BearerCredential) DeepCopyInto(out *BearerCredential) {
	*out = *in
	out.ValueSecretRef = in.ValueSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BearerCredential.
func (in *BearerCredential) DeepCopy() *BearerCredential {
	if in == nil {
		return nil
	}
	out := new(BearerCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Binding) DeepCopyInto(out *Binding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Binding.
func (in *Binding) DeepCopy() *Binding {
	if in == nil {
		return nil
	}
	out := new(Binding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialBinding) DeepCopyInto(out *CredentialBinding) {
	*out = *in
	if in.Bearer != nil {
		in, out := &in.Bearer, &out.Bearer
		*out = new(BearerCredential)
		**out = **in
	}
	if in.OAuth != nil {
		in, out := &in.OAuth, &out.OAuth
		*out = new(OAuthClientCredentials)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceConstraints != nil {
		in, out := &in.ResourceConstraints, &out.ResourceConstraints
		*out = make([]ResourceConstraint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialBinding.
func (in *CredentialBinding) DeepCopy() *CredentialBinding {
	if in == nil {
		return nil
	}
	out := new(CredentialBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalBackendSpec) DeepCopyInto(out *ExternalBackendSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalBackendSpec.
func (in *ExternalBackendSpec) DeepCopy() *ExternalBackendSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayEndpoint) DeepCopyInto(out *GatewayEndpoint) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayEndpoint.
func (in *GatewayEndpoint) DeepCopy() *GatewayEndpoint {
	if in == nil {
		return nil
	}
	out := new(GatewayEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayGrant) DeepCopyInto(out *GatewayGrant) {
	*out = *in
	if in.AllowedActions != nil {
		in, out := &in.AllowedActions, &out.AllowedActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayGrant.
func (in *GatewayGrant) DeepCopy() *GatewayGrant {
	if in == nil {
		return nil
	}
	out := new(GatewayGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayPodSelector) DeepCopyInto(out *GatewayPodSelector) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.PodSelector.DeepCopyInto(&out.PodSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayPodSelector.
func (in *GatewayPodSelector) DeepCopy() *GatewayPodSelector {
	if in == nil {
		return nil
	}
	out := new(GatewayPodSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphEmailTriggerBinding) DeepCopyInto(out *GraphEmailTriggerBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphEmailTriggerBinding.
func (in *GraphEmailTriggerBinding) DeepCopy() *GraphEmailTriggerBinding {
	if in == nil {
		return nil
	}
	out := new(GraphEmailTriggerBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthProbeSpec) DeepCopyInto(out *HealthProbeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthProbeSpec.
func (in *HealthProbeSpec) DeepCopy() *HealthProbeSpec {
	if in == nil {
		return nil
	}
	out := new(HealthProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumanGateFieldPresentation) DeepCopyInto(out *HumanGateFieldPresentation) {
	*out = *in
	out.Label = in.Label
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]LocalizedText, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumanGateFieldPresentation.
func (in *HumanGateFieldPresentation) DeepCopy() *HumanGateFieldPresentation {
	if in == nil {
		return nil
	}
	out := new(HumanGateFieldPresentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumanGatePresentation) DeepCopyInto(out *HumanGatePresentation) {
	*out = *in
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]LocalizedText, len(*in))
		copy(*out, *in)
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]HumanGateFieldPresentation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumanGatePresentation.
func (in *HumanGatePresentation) DeepCopy() *HumanGatePresentation {
	if in == nil {
		return nil
	}
	out := new(HumanGatePresentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumanGateSpec) DeepCopyInto(out *HumanGateSpec) {
	*out = *in
	out.Title = in.Title
	out.Description = in.Description
	if in.ResponseSchema != nil {
		in, out := &in.ResponseSchema, &out.ResponseSchema
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	in.Presentation.DeepCopyInto(&out.Presentation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumanGateSpec.
func (in *HumanGateSpec) DeepCopy() *HumanGateSpec {
	if in == nil {
		return nil
	}
	out := new(HumanGateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityMapping) DeepCopyInto(out *IdentityMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityMapping.
func (in *IdentityMapping) DeepCopy() *IdentityMapping {
	if in == nil {
		return nil
	}
	out := new(IdentityMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityMappingList) DeepCopyInto(out *IdentityMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IdentityMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityMappingList.
func (in *IdentityMappingList) DeepCopy() *IdentityMappingList {
	if in == nil {
		return nil
	}
	out := new(IdentityMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IdentityMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityMappingSpec) DeepCopyInto(out *IdentityMappingSpec) {
	*out = *in
	out.Identity = in.Identity
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]Binding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityMappingSpec.
func (in *IdentityMappingSpec) DeepCopy() *IdentityMappingSpec {
	if in == nil {
		return nil
	}
	out := new(IdentityMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityMappingStatus) DeepCopyInto(out *IdentityMappingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityMappingStatus.
func (in *IdentityMappingStatus) DeepCopy() *IdentityMappingStatus {
	if in == nil {
		return nil
	}
	out := new(IdentityMappingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentitySpec) DeepCopyInto(out *IdentitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentitySpec.
func (in *IdentitySpec) DeepCopy() *IdentitySpec {
	if in == nil {
		return nil
	}
	out := new(IdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalKeyRef) DeepCopyInto(out *LocalKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalKeyRef.
func (in *LocalKeyRef) DeepCopy() *LocalKeyRef {
	if in == nil {
		return nil
	}
	out := new(LocalKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalizedText) DeepCopyInto(out *LocalizedText) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalizedText.
func (in *LocalizedText) DeepCopy() *LocalizedText {
	if in == nil {
		return nil
	}
	out := new(LocalizedText)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Model) DeepCopyInto(out *Model) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Model.
func (in *Model) DeepCopy() *Model {
	if in == nil {
		return nil
	}
	out := new(Model)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Model) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelBackend) DeepCopyInto(out *ModelBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelBackend.
func (in *ModelBackend) DeepCopy() *ModelBackend {
	if in == nil {
		return nil
	}
	out := new(ModelBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelBackendList) DeepCopyInto(out *ModelBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelBackendList.
func (in *ModelBackendList) DeepCopy() *ModelBackendList {
	if in == nil {
		return nil
	}
	out := new(ModelBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelBackendSpec) DeepCopyInto(out *ModelBackendSpec) {
	*out = *in
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DevShmSize != nil {
		in, out := &in.DevShmSize, &out.DevShmSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.HealthProbe != nil {
		in, out := &in.HealthProbe, &out.HealthProbe
		*out = new(HealthProbeSpec)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalBackendSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelBackendSpec.
func (in *ModelBackendSpec) DeepCopy() *ModelBackendSpec {
	if in == nil {
		return nil
	}
	out := new(ModelBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelBackendStatus) DeepCopyInto(out *ModelBackendStatus) {
	*out = *in
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelBackendStatus.
func (in *ModelBackendStatus) DeepCopy() *ModelBackendStatus {
	if in == nil {
		return nil
	}
	out := new(ModelBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDefaultParams) DeepCopyInto(out *ModelDefaultParams) {
	*out = *in
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(float64)
		**out = **in
	}
	if in.TopP != nil {
		in, out := &in.TopP, &out.TopP
		*out = new(float64)
		**out = **in
	}
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int)
		**out = **in
	}
	if in.FrequencyPenalty != nil {
		in, out := &in.FrequencyPenalty, &out.FrequencyPenalty
		*out = new(float64)
		**out = **in
	}
	if in.PresencePenalty != nil {
		in, out := &in.PresencePenalty, &out.PresencePenalty
		*out = new(float64)
		**out = **in
	}
	if in.RepetitionPenalty != nil {
		in, out := &in.RepetitionPenalty, &out.RepetitionPenalty
		*out = new(float64)
		**out = **in
	}
	if in.TopK != nil {
		in, out := &in.TopK, &out.TopK
		*out = new(int)
		**out = **in
	}
	if in.MinP != nil {
		in, out := &in.MinP, &out.MinP
		*out = new(float64)
		**out = **in
	}
	if in.Stop != nil {
		in, out := &in.Stop, &out.Stop
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDefaultParams.
func (in *ModelDefaultParams) DeepCopy() *ModelDefaultParams {
	if in == nil {
		return nil
	}
	out := new(ModelDefaultParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelList) DeepCopyInto(out *ModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Model, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelList.
func (in *ModelList) DeepCopy() *ModelList {
	if in == nil {
		return nil
	}
	out := new(ModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRateLimits) DeepCopyInto(out *ModelRateLimits) {
	*out = *in
	if in.RPM != nil {
		in, out := &in.RPM, &out.RPM
		*out = new(int)
		**out = **in
	}
	if in.TPM != nil {
		in, out := &in.TPM, &out.TPM
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRateLimits.
func (in *ModelRateLimits) DeepCopy() *ModelRateLimits {
	if in == nil {
		return nil
	}
	out := new(ModelRateLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelReasoningConfig) DeepCopyInto(out *ModelReasoningConfig) {
	*out = *in
	if in.EnableThinking != nil {
		in, out := &in.EnableThinking, &out.EnableThinking
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelReasoningConfig.
func (in *ModelReasoningConfig) DeepCopy() *ModelReasoningConfig {
	if in == nil {
		return nil
	}
	out := new(ModelReasoningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.DefaultParams.DeepCopyInto(&out.DefaultParams)
	in.ReasoningConfig.DeepCopyInto(&out.ReasoningConfig)
	out.Transforms = in.Transforms
	in.RateLimits.DeepCopyInto(&out.RateLimits)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelStatus) DeepCopyInto(out *ModelStatus) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelStatus.
func (in *ModelStatus) DeepCopy() *ModelStatus {
	if in == nil {
		return nil
	}
	out := new(ModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelTransforms) DeepCopyInto(out *ModelTransforms) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelTransforms.
func (in *ModelTransforms) DeepCopy() *ModelTransforms {
	if in == nil {
		return nil
	}
	out := new(ModelTransforms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.DnsSelector != nil {
		in, out := &in.DnsSelector, &out.DnsSelector
		*out = new(GatewayPodSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthClientCredentials) DeepCopyInto(out *OAuthClientCredentials) {
	*out = *in
	out.ClientSecretRef = in.ClientSecretRef
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthClientCredentials.
func (in *OAuthClientCredentials) DeepCopy() *OAuthClientCredentials {
	if in == nil {
		return nil
	}
	out := new(OAuthClientCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorArtifactTriggerBinding) DeepCopyInto(out *OperatorArtifactTriggerBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorArtifactTriggerBinding.
func (in *OperatorArtifactTriggerBinding) DeepCopy() *OperatorArtifactTriggerBinding {
	if in == nil {
		return nil
	}
	out := new(OperatorArtifactTriggerBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionPolicy) DeepCopyInto(out *PermissionPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionPolicy.
func (in *PermissionPolicy) DeepCopy() *PermissionPolicy {
	if in == nil {
		return nil
	}
	out := new(PermissionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PermissionPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionPolicyList) DeepCopyInto(out *PermissionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PermissionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionPolicyList.
func (in *PermissionPolicyList) DeepCopy() *PermissionPolicyList {
	if in == nil {
		return nil
	}
	out := new(PermissionPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PermissionPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionPolicySpec) DeepCopyInto(out *PermissionPolicySpec) {
	*out = *in
	out.Subject = in.Subject
	if in.RateLimits != nil {
		in, out := &in.RateLimits, &out.RateLimits
		*out = new(RateLimitsSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionPolicySpec.
func (in *PermissionPolicySpec) DeepCopy() *PermissionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PermissionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionPolicyStatus) DeepCopyInto(out *PermissionPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionPolicyStatus.
func (in *PermissionPolicyStatus) DeepCopy() *PermissionPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PermissionPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolGatewaysSpec) DeepCopyInto(out *PoolGatewaysSpec) {
	*out = *in
	in.ControlPlane.DeepCopyInto(&out.ControlPlane)
	in.ToolGateway.DeepCopyInto(&out.ToolGateway)
	in.InferenceGateway.DeepCopyInto(&out.InferenceGateway)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolGatewaysSpec.
func (in *PoolGatewaysSpec) DeepCopy() *PoolGatewaysSpec {
	if in == nil {
		return nil
	}
	out := new(PoolGatewaysSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolIdentitySpec) DeepCopyInto(out *PoolIdentitySpec) {
	*out = *in
	out.CASecretRef = in.CASecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolIdentitySpec.
func (in *PoolIdentitySpec) DeepCopy() *PoolIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(PoolIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolProbeSpec) DeepCopyInto(out *PoolProbeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolProbeSpec.
func (in *PoolProbeSpec) DeepCopy() *PoolProbeSpec {
	if in == nil {
		return nil
	}
	out := new(PoolProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresentationSpec) DeepCopyInto(out *PresentationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresentationSpec.
func (in *PresentationSpec) DeepCopy() *PresentationSpec {
	if in == nil {
		return nil
	}
	out := new(PresentationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitsSpec) DeepCopyInto(out *RateLimitsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitsSpec.
func (in *RateLimitsSpec) DeepCopy() *RateLimitsSpec {
	if in == nil {
		return nil
	}
	out := new(RateLimitsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestedCapability) DeepCopyInto(out *RequestedCapability) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestedCapability.
func (in *RequestedCapability) DeepCopy() *RequestedCapability {
	if in == nil {
		return nil
	}
	out := new(RequestedCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConstraint) DeepCopyInto(out *ResourceConstraint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConstraint.
func (in *ResourceConstraint) DeepCopy() *ResourceConstraint {
	if in == nil {
		return nil
	}
	out := new(ResourceConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultFieldPresentation) DeepCopyInto(out *ResultFieldPresentation) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Label = in.Label
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]ResultValuePresentation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultFieldPresentation.
func (in *ResultFieldPresentation) DeepCopy() *ResultFieldPresentation {
	if in == nil {
		return nil
	}
	out := new(ResultFieldPresentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultOutcomePresentation) DeepCopyInto(out *ResultOutcomePresentation) {
	*out = *in
	out.Summary = in.Summary
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultOutcomePresentation.
func (in *ResultOutcomePresentation) DeepCopy() *ResultOutcomePresentation {
	if in == nil {
		return nil
	}
	out := new(ResultOutcomePresentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultPresentation) DeepCopyInto(out *ResultPresentation) {
	*out = *in
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]ResultOutcomePresentation, len(*in))
		copy(*out, *in)
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]ResultFieldPresentation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultPresentation.
func (in *ResultPresentation) DeepCopy() *ResultPresentation {
	if in == nil {
		return nil
	}
	out := new(ResultPresentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultValuePresentation) DeepCopyInto(out *ResultValuePresentation) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
	out.Label = in.Label
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultValuePresentation.
func (in *ResultValuePresentation) DeepCopy() *ResultValuePresentation {
	if in == nil {
		return nil
	}
	out := new(ResultValuePresentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSpec) DeepCopyInto(out *SandboxSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSpec.
func (in *SandboxSpec) DeepCopy() *SandboxSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillReference) DeepCopyInto(out *SkillReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillReference.
func (in *SkillReference) DeepCopy() *SkillReference {
	if in == nil {
		return nil
	}
	out := new(SkillReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectSpec) DeepCopyInto(out *SubjectSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectSpec.
func (in *SubjectSpec) DeepCopy() *SubjectSpec {
	if in == nil {
		return nil
	}
	out := new(SubjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerBinding) DeepCopyInto(out *TriggerBinding) {
	*out = *in
	if in.GraphEmail != nil {
		in, out := &in.GraphEmail, &out.GraphEmail
		*out = new(GraphEmailTriggerBinding)
		**out = **in
	}
	if in.OperatorArtifact != nil {
		in, out := &in.OperatorArtifact, &out.OperatorArtifact
		*out = new(OperatorArtifactTriggerBinding)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerBinding.
func (in *TriggerBinding) DeepCopy() *TriggerBinding {
	if in == nil {
		return nil
	}
	out := new(TriggerBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workflow) DeepCopyInto(out *Workflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workflow.
func (in *Workflow) DeepCopy() *Workflow {
	if in == nil {
		return nil
	}
	out := new(Workflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Workflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowEdge) DeepCopyInto(out *WorkflowEdge) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowEdge.
func (in *WorkflowEdge) DeepCopy() *WorkflowEdge {
	if in == nil {
		return nil
	}
	out := new(WorkflowEdge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowGraph) DeepCopyInto(out *WorkflowGraph) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]WorkflowNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Edges != nil {
		in, out := &in.Edges, &out.Edges
		*out = make([]WorkflowEdge, len(*in))
		copy(*out, *in)
	}
	if in.TerminalOutcomes != nil {
		in, out := &in.TerminalOutcomes, &out.TerminalOutcomes
		*out = make([]WorkflowTerminalOutcome, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowGraph.
func (in *WorkflowGraph) DeepCopy() *WorkflowGraph {
	if in == nil {
		return nil
	}
	out := new(WorkflowGraph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowList) DeepCopyInto(out *WorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Workflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowList.
func (in *WorkflowList) DeepCopy() *WorkflowList {
	if in == nil {
		return nil
	}
	out := new(WorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowNode) DeepCopyInto(out *WorkflowNode) {
	*out = *in
	out.Label = in.Label
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OutputSchema != nil {
		in, out := &in.OutputSchema, &out.OutputSchema
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ResultPresentation != nil {
		in, out := &in.ResultPresentation, &out.ResultPresentation
		*out = new(ResultPresentation)
		(*in).DeepCopyInto(*out)
	}
	if in.HumanGate != nil {
		in, out := &in.HumanGate, &out.HumanGate
		*out = new(HumanGateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowNode.
func (in *WorkflowNode) DeepCopy() *WorkflowNode {
	if in == nil {
		return nil
	}
	out := new(WorkflowNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowSource) DeepCopyInto(out *WorkflowSource) {
	*out = *in
	if in.TriggerBindings != nil {
		in, out := &in.TriggerBindings, &out.TriggerBindings
		*out = make([]TriggerBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowSource.
func (in *WorkflowSource) DeepCopy() *WorkflowSource {
	if in == nil {
		return nil
	}
	out := new(WorkflowSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowSpec) DeepCopyInto(out *WorkflowSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Graph.DeepCopyInto(&out.Graph)
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]SkillReference, len(*in))
		copy(*out, *in)
	}
	if in.RequestedCapabilities != nil {
		in, out := &in.RequestedCapabilities, &out.RequestedCapabilities
		*out = make([]RequestedCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Presentation = in.Presentation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowSpec.
func (in *WorkflowSpec) DeepCopy() *WorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(WorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowStatus) DeepCopyInto(out *WorkflowStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowStatus.
func (in *WorkflowStatus) DeepCopy() *WorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(WorkflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowTerminalOutcome) DeepCopyInto(out *WorkflowTerminalOutcome) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowTerminalOutcome.
func (in *WorkflowTerminalOutcome) DeepCopy() *WorkflowTerminalOutcome {
	if in == nil {
		return nil
	}
	out := new(WorkflowTerminalOutcome)
	in.DeepCopyInto(out)
	return out
}
