{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.name" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: 5432
{{- end }}
