# This kustomization.yaml is not intended to be run by itself,
# since it depends on all CRDs being installed first (make install).
# It exists so config/default can include the CRDs.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/platform.iterabase.com_identitymappings.yaml
- bases/platform.iterabase.com_modelbackends.yaml
- bases/platform.iterabase.com_permissionpolicies.yaml
- bases/platform.iterabase.com_workflows.yaml
