apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: iterabase-lvm-snapshot
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "false"
    iterabase.com/architecture-decision: DES-HOR-545-04
driver: local.csi.openebs.io
deletionPolicy: Delete
parameters:
  snapSize: 100%
